import { Cuerda, Gallo, Torneo, TipoGallo, TipoEdad } from './types';

// Data provided by the user as an example.
const preloadedJSON = {
  "torneo": {
    "name": "Gran Torneo Internacional",
    "tournamentManager": "Organizador Principal",
    "date": "2024-08-15",
    "weightTolerance": 2,
    "ageToleranceMonths": 1,
    "minWeight": 45,
    "maxWeight": 64,
    "roostersPerTeam": 6,
    "pointsForWin": 3,
    "pointsForDraw": 1,
    "tournamentDays": 3,
    "exceptions": []
  },
  "cuerdas": [
    { "id": "cuerda-1", "name": "Los Titanes (F1)", "owner": "Carlos Rojas", "city": "Medellín" },
    { "id": "cuerda-2", "name": "Furia Roja (F1)", "owner": "Andrés Gil", "city": "Bogotá" },
    { "id": "cuerda-3", "name": "Acero del Valle (F1)", "owner": "Javier Solís", "city": "Cali" },
    { "id": "cuerda-4", "name": "Costa Brava (F1)", "owner": "Ricardo Montes", "city": "Barranquilla" },
    { "id": "cuerda-5", "name": "Espuela Dorada (F1)", "owner": "Luis Fernández", "city": "Cartagena" },
    { "id": "cuerda-6", "name": "Hijos del Viento (F1)", "owner": "Mateo Correa", "city": "Cúcuta" },
    { "id": "cuerda-7", "name": "Galleros de Santander (F1)", "owner": "Simón Díaz", "city": "Bucaramanga" },
    { "id": "cuerda-8", "name": "Eje Cafetero (F1)", "owner": "Daniel Puentes", "city": "Pereira" },
    { "id": "cuerda-9", "name": "Fénix de Fuego (F1)", "owner": "Oscar Rentería", "city": "Ibagué" },
    { "id": "cuerda-10", "name": "Relámpagos (F1)", "owner": "Jorge Vélez", "city": "Manizales" },
    { "id": "cuerda-11", "name": "Centuriones (F1)", "owner": "Felipe Arias", "city": "Pasto" },
    { "id": "cuerda-12", "name": "Dinastía Giraldo (F1)", "owner": "Hernán Giraldo", "city": "Neiva" },
    { "id": "cuerda-13", "name": "Llaneros de Acero (F1)", "owner": "Pedro Infante", "city": "Villavicencio" },
    { "id": "cuerda-14", "name": "Hermanos Pineda (F1)", "owner": "Hugo Pineda", "city": "Armenia" },
    { "id": "cuerda-15", "name": "La Fortaleza (F1)", "owner": "Sergio Castillo", "city": "Medellín" },
    { "id": "cuerda-16", "name": "El Retorno (F1)", "owner": "Camilo Torres", "city": "Bogotá" },
    { "id": "cuerda-17", "name": "Pura Casta (F1)", "owner": "Iván Duque", "city": "Cali" },
    { "id": "cuerda-18", "name": "Navajeros del Caribe (F1)", "owner": "Martín Elías", "city": "Barranquilla" },
    { "id": "cuerda-19", "name": "Los Inmortales (F1)", "owner": "Juan Valdés", "city": "Cartagena" },
    { "id": "cuerda-20", "name": "Gladiadores (F1)", "owner": "David Ospina", "city": "Cúcuta" },
    { "id": "cuerda-21", "name": "Sangre y Fuego (F1)", "owner": "James Rodríguez", "city": "Bucaramanga" },
    { "id": "cuerda-22", "name": "Vencedores (F1)", "owner": "Falcao García", "city": "Pereira" },
    { "id": "cuerda-23", "name": "La Leyenda (F1)", "owner": "Nairo Quintana", "city": "Ibagué" },
    { "id": "cuerda-24", "name": "El Ciclón (F1)", "owner": "Egan Bernal", "city": "Manizales" },
    { "id": "cuerda-25", "name": "Tornado (F1)", "owner": "Rigoberto Urán", "city": "Pasto" },
    { "id": "cuerda-26", "name": "Furia Latina (F1)", "owner": "Maluma", "city": "Neiva" },
    { "id": "cuerda-27", "name": "Los Paisas (F1)", "owner": "J Balvin", "city": "Villavicencio" },
    { "id": "cuerda-28", "name": "Reyes del Ruedo (F1)", "owner": "Shakira", "city": "Armenia" },
    { "id": "cuerda-29", "name": "Casta de Campeones (F1)", "owner": "Carlos Vives", "city": "Medellín" },
    { "id": "cuerda-30", "name": "Demonios Rojos (F1)", "owner": "Juanes", "city": "Bogotá" }
  ],
  "gallosByDay": {
    "1": [
      { "id": "gallo-1-1", "ringId": "1011", "color": "Jiro", "cuerdaId": "cuerda-1", "weight": 50, "ageMonths": 14, "markingId": "PM111", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-1-2", "ringId": "1012", "color": "Colorado", "cuerdaId": "cuerda-1", "weight": 60, "ageMonths": 18, "markingId": "PM112", "breederPlateId": "PC101", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-2-1", "ringId": "1021", "color": "Cenizo", "cuerdaId": "cuerda-2", "weight": 46, "ageMonths": 15, "markingId": "PM121", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-2-2", "ringId": "1022", "color": "Pinto", "cuerdaId": "cuerda-2", "weight": 55, "ageMonths": 16, "markingId": "PM122", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-3-1", "ringId": "1031", "color": "Blanco", "cuerdaId": "cuerda-3", "weight": 62, "ageMonths": 13, "markingId": "PM131", "breederPlateId": "PC103", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-3-2", "ringId": "1032", "color": "Negro", "cuerdaId": "cuerda-3", "weight": 58, "ageMonths": 17, "markingId": "PM132", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-4-1", "ringId": "1041", "color": "Canelo", "cuerdaId": "cuerda-4", "weight": 48, "ageMonths": 12, "markingId": "PM141", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-4-2", "ringId": "1042", "color": "Moro", "cuerdaId": "cuerda-4", "weight": 53, "ageMonths": 19, "markingId": "PM142", "breederPlateId": "PC104", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-5-1", "ringId": "1051", "color": "Búlico", "cuerdaId": "cuerda-5", "weight": 51, "ageMonths": 20, "markingId": "PM151", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-5-2", "ringId": "1052", "color": "Jiro", "cuerdaId": "cuerda-5", "weight": 59, "ageMonths": 14, "markingId": "PM152", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-6-1", "ringId": "1061", "color": "Colorado", "cuerdaId": "cuerda-6", "weight": 47, "ageMonths": 15, "markingId": "PM161", "breederPlateId": "PC106", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-6-2", "ringId": "1062", "color": "Cenizo", "cuerdaId": "cuerda-6", "weight": 54, "ageMonths": 16, "markingId": "PM162", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-7-1", "ringId": "1071", "color": "Pinto", "cuerdaId": "cuerda-7", "weight": 63, "ageMonths": 13, "markingId": "PM171", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-7-2", "ringId": "1072", "color": "Blanco", "cuerdaId": "cuerda-7", "weight": 57, "ageMonths": 18, "markingId": "PM172", "breederPlateId": "PC107", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-8-1", "ringId": "1081", "color": "Negro", "cuerdaId": "cuerda-8", "weight": 49, "ageMonths": 17, "markingId": "PM181", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-8-2", "ringId": "1082", "color": "Canelo", "cuerdaId": "cuerda-8", "weight": 56, "ageMonths": 12, "markingId": "PM182", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-9-1", "ringId": "1091", "color": "Moro", "cuerdaId": "cuerda-9", "weight": 52, "ageMonths": 19, "markingId": "PM191", "breederPlateId": "PC109", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-9-2", "ringId": "1092", "color": "Búlico", "cuerdaId": "cuerda-9", "weight": 61, "ageMonths": 20, "markingId": "PM192", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-10-1", "ringId": "1101", "color": "Jiro", "cuerdaId": "cuerda-10", "weight": 45, "ageMonths": 14, "markingId": "PM201", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-10-2", "ringId": "1102", "color": "Colorado", "cuerdaId": "cuerda-10", "weight": 64, "ageMonths": 18, "markingId": "PM202", "breederPlateId": "PC110", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-11-1", "ringId": "1111", "color": "Jiro", "cuerdaId": "cuerda-11", "weight": 50, "ageMonths": 14, "markingId": "PM111", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-11-2", "ringId": "1112", "color": "Colorado", "cuerdaId": "cuerda-11", "weight": 60, "ageMonths": 18, "markingId": "PM112", "breederPlateId": "PC101", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-12-1", "ringId": "1121", "color": "Cenizo", "cuerdaId": "cuerda-12", "weight": 46, "ageMonths": 15, "markingId": "PM121", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-12-2", "ringId": "1122", "color": "Pinto", "cuerdaId": "cuerda-12", "weight": 55, "ageMonths": 16, "markingId": "PM122", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-13-1", "ringId": "1131", "color": "Blanco", "cuerdaId": "cuerda-13", "weight": 62, "ageMonths": 13, "markingId": "PM131", "breederPlateId": "PC103", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-13-2", "ringId": "1132", "color": "Negro", "cuerdaId": "cuerda-13", "weight": 58, "ageMonths": 17, "markingId": "PM132", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-14-1", "ringId": "1141", "color": "Canelo", "cuerdaId": "cuerda-14", "weight": 48, "ageMonths": 12, "markingId": "PM141", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-14-2", "ringId": "1142", "color": "Moro", "cuerdaId": "cuerda-14", "weight": 53, "ageMonths": 19, "markingId": "PM142", "breederPlateId": "PC104", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-15-1", "ringId": "1151", "color": "Búlico", "cuerdaId": "cuerda-15", "weight": 51, "ageMonths": 20, "markingId": "PM151", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-15-2", "ringId": "1152", "color": "Jiro", "cuerdaId": "cuerda-15", "weight": 59, "ageMonths": 14, "markingId": "PM152", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-16-1", "ringId": "1161", "color": "Colorado", "cuerdaId": "cuerda-16", "weight": 47, "ageMonths": 15, "markingId": "PM161", "breederPlateId": "PC106", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-16-2", "ringId": "1162", "color": "Cenizo", "cuerdaId": "cuerda-16", "weight": 54, "ageMonths": 16, "markingId": "PM162", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-17-1", "ringId": "1171", "color": "Pinto", "cuerdaId": "cuerda-17", "weight": 63, "ageMonths": 13, "markingId": "PM171", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-17-2", "ringId": "1172", "color": "Blanco", "cuerdaId": "cuerda-17", "weight": 57, "ageMonths": 18, "markingId": "PM172", "breederPlateId": "PC107", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-18-1", "ringId": "1181", "color": "Negro", "cuerdaId": "cuerda-18", "weight": 49, "ageMonths": 17, "markingId": "PM181", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-18-2", "ringId": "1182", "color": "Canelo", "cuerdaId": "cuerda-18", "weight": 56, "ageMonths": 12, "markingId": "PM182", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-19-1", "ringId": "1191", "color": "Moro", "cuerdaId": "cuerda-19", "weight": 52, "ageMonths": 19, "markingId": "PM191", "breederPlateId": "PC109", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-19-2", "ringId": "1192", "color": "Búlico", "cuerdaId": "cuerda-19", "weight": 61, "ageMonths": 20, "markingId": "PM192", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-20-1", "ringId": "1201", "color": "Jiro", "cuerdaId": "cuerda-20", "weight": 45, "ageMonths": 14, "markingId": "PM201", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-20-2", "ringId": "1202", "color": "Colorado", "cuerdaId": "cuerda-20", "weight": 64, "ageMonths": 18, "markingId": "PM202", "breederPlateId": "PC110", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-21-1", "ringId": "1211", "color": "Jiro", "cuerdaId": "cuerda-21", "weight": 50, "ageMonths": 14, "markingId": "PM111", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-21-2", "ringId": "1212", "color": "Colorado", "cuerdaId": "cuerda-21", "weight": 60, "ageMonths": 18, "markingId": "PM112", "breederPlateId": "PC101", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-22-1", "ringId": "1221", "color": "Cenizo", "cuerdaId": "cuerda-22", "weight": 46, "ageMonths": 15, "markingId": "PM121", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-22-2", "ringId": "1222", "color": "Pinto", "cuerdaId": "cuerda-22", "weight": 55, "ageMonths": 16, "markingId": "PM122", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-23-1", "ringId": "1231", "color": "Blanco", "cuerdaId": "cuerda-23", "weight": 62, "ageMonths": 13, "markingId": "PM131", "breederPlateId": "PC103", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-23-2", "ringId": "1232", "color": "Negro", "cuerdaId": "cuerda-23", "weight": 58, "ageMonths": 17, "markingId": "PM132", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-24-1", "ringId": "1241", "color": "Canelo", "cuerdaId": "cuerda-24", "weight": 48, "ageMonths": 12, "markingId": "PM141", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-24-2", "ringId": "1242", "color": "Moro", "cuerdaId": "cuerda-24", "weight": 53, "ageMonths": 19, "markingId": "PM142", "breederPlateId": "PC104", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-25-1", "ringId": "1251", "color": "Búlico", "cuerdaId": "cuerda-25", "weight": 51, "ageMonths": 20, "markingId": "PM151", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-25-2", "ringId": "1252", "color": "Jiro", "cuerdaId": "cuerda-25", "weight": 59, "ageMonths": 14, "markingId": "PM152", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-26-1", "ringId": "1261", "color": "Colorado", "cuerdaId": "cuerda-26", "weight": 47, "ageMonths": 15, "markingId": "PM161", "breederPlateId": "PC106", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-26-2", "ringId": "1262", "color": "Cenizo", "cuerdaId": "cuerda-26", "weight": 54, "ageMonths": 16, "markingId": "PM162", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-27-1", "ringId": "1271", "color": "Pinto", "cuerdaId": "cuerda-27", "weight": 63, "ageMonths": 13, "markingId": "PM171", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-27-2", "ringId": "1272", "color": "Blanco", "cuerdaId": "cuerda-27", "weight": 57, "ageMonths": 18, "markingId": "PM172", "breederPlateId": "PC107", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-28-1", "ringId": "1281", "color": "Negro", "cuerdaId": "cuerda-28", "weight": 49, "ageMonths": 17, "markingId": "PM181", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-28-2", "ringId": "1282", "color": "Canelo", "cuerdaId": "cuerda-28", "weight": 56, "ageMonths": 12, "markingId": "PM182", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-29-1", "ringId": "1291", "color": "Moro", "cuerdaId": "cuerda-29", "weight": 52, "ageMonths": 19, "markingId": "PM191", "breederPlateId": "PC109", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-29-2", "ringId": "1292", "color": "Búlico", "cuerdaId": "cuerda-29", "weight": 61, "ageMonths": 20, "markingId": "PM192", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-30-1", "ringId": "1301", "color": "Jiro", "cuerdaId": "cuerda-30", "weight": 45, "ageMonths": 14, "markingId": "PM201", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-30-2", "ringId": "1302", "color": "Colorado", "cuerdaId": "cuerda-30", "weight": 64, "ageMonths": 18, "markingId": "PM202", "breederPlateId": "PC110", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 }
    ],
    "2": [
      { "id": "gallo-1-3", "ringId": "2013", "color": "Cenizo", "cuerdaId": "cuerda-1", "weight": 51, "ageMonths": 15, "markingId": "PM213", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-1-4", "ringId": "2014", "color": "Pinto", "cuerdaId": "cuerda-1", "weight": 58, "ageMonths": 16, "markingId": "PM214", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-2-3", "ringId": "2023", "color": "Blanco", "cuerdaId": "cuerda-2", "weight": 61, "ageMonths": 13, "markingId": "PM223", "breederPlateId": "PC102", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-2-4", "ringId": "2024", "color": "Negro", "cuerdaId": "cuerda-2", "weight": 59, "ageMonths": 17, "markingId": "PM224", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-3-3", "ringId": "2033", "color": "Canelo", "cuerdaId": "cuerda-3", "weight": 47, "ageMonths": 12, "markingId": "PM233", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-3-4", "ringId": "2034", "color": "Moro", "cuerdaId": "cuerda-3", "weight": 54, "ageMonths": 19, "markingId": "PM234", "breederPlateId": "PC103", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-4-3", "ringId": "2043", "color": "Búlico", "cuerdaId": "cuerda-4", "weight": 52, "ageMonths": 20, "markingId": "PM243", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-4-4", "ringId": "2044", "color": "Jiro", "cuerdaId": "cuerda-4", "weight": 60, "ageMonths": 14, "markingId": "PM244", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-5-3", "ringId": "2053", "color": "Colorado", "cuerdaId": "cuerda-5", "weight": 46, "ageMonths": 15, "markingId": "PM253", "breederPlateId": "PC105", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-5-4", "ringId": "2054", "color": "Cenizo", "cuerdaId": "cuerda-5", "weight": 56, "ageMonths": 16, "markingId": "PM254", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-6-3", "ringId": "2063", "color": "Pinto", "cuerdaId": "cuerda-6", "weight": 63, "ageMonths": 13, "markingId": "PM263", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-6-4", "ringId": "2064", "color": "Blanco", "cuerdaId": "cuerda-6", "weight": 57, "ageMonths": 18, "markingId": "PM264", "breederPlateId": "PC106", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-7-3", "ringId": "2073", "color": "Negro", "cuerdaId": "cuerda-7", "weight": 49, "ageMonths": 17, "markingId": "PM273", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-7-4", "ringId": "2074", "color": "Canelo", "cuerdaId": "cuerda-7", "weight": 55, "ageMonths": 12, "markingId": "PM274", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-8-3", "ringId": "2083", "color": "Moro", "cuerdaId": "cuerda-8", "weight": 53, "ageMonths": 19, "markingId": "PM283", "breederPlateId": "PC108", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-8-4", "ringId": "2084", "color": "Búlico", "cuerdaId": "cuerda-8", "weight": 61, "ageMonths": 20, "markingId": "PM284", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-9-3", "ringId": "2093", "color": "Jiro", "cuerdaId": "cuerda-9", "weight": 45, "ageMonths": 14, "markingId": "PM293", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-9-4", "ringId": "2094", "color": "Colorado", "cuerdaId": "cuerda-9", "weight": 64, "ageMonths": 18, "markingId": "PM294", "breederPlateId": "PC109", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-10-3", "ringId": "2103", "color": "Cenizo", "cuerdaId": "cuerda-10", "weight": 50, "ageMonths": 15, "markingId": "PM303", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-10-4", "ringId": "2104", "color": "Pinto", "cuerdaId": "cuerda-10", "weight": 58, "ageMonths": 16, "markingId": "PM304", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-11-3", "ringId": "2113", "color": "Cenizo", "cuerdaId": "cuerda-11", "weight": 51, "ageMonths": 15, "markingId": "PM213", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-11-4", "ringId": "2114", "color": "Pinto", "cuerdaId": "cuerda-11", "weight": 58, "ageMonths": 16, "markingId": "PM214", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-12-3", "ringId": "2123", "color": "Blanco", "cuerdaId": "cuerda-12", "weight": 61, "ageMonths": 13, "markingId": "PM223", "breederPlateId": "PC102", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-12-4", "ringId": "2124", "color": "Negro", "cuerdaId": "cuerda-12", "weight": 59, "ageMonths": 17, "markingId": "PM224", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-13-3", "ringId": "2133", "color": "Canelo", "cuerdaId": "cuerda-13", "weight": 47, "ageMonths": 12, "markingId": "PM233", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-13-4", "ringId": "2134", "color": "Moro", "cuerdaId": "cuerda-13", "weight": 54, "ageMonths": 19, "markingId": "PM234", "breederPlateId": "PC103", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-14-3", "ringId": "2143", "color": "Búlico", "cuerdaId": "cuerda-14", "weight": 52, "ageMonths": 20, "markingId": "PM243", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-14-4", "ringId": "2144", "color": "Jiro", "cuerdaId": "cuerda-14", "weight": 60, "ageMonths": 14, "markingId": "PM244", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-15-3", "ringId": "2153", "color": "Colorado", "cuerdaId": "cuerda-15", "weight": 46, "ageMonths": 15, "markingId": "PM253", "breederPlateId": "PC105", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-15-4", "ringId": "2154", "color": "Cenizo", "cuerdaId": "cuerda-15", "weight": 56, "ageMonths": 16, "markingId": "PM254", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-16-3", "ringId": "2163", "color": "Pinto", "cuerdaId": "cuerda-16", "weight": 63, "ageMonths": 13, "markingId": "PM263", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-16-4", "ringId": "2164", "color": "Blanco", "cuerdaId": "cuerda-16", "weight": 57, "ageMonths": 18, "markingId": "PM264", "breederPlateId": "PC106", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-17-3", "ringId": "2173", "color": "Negro", "cuerdaId": "cuerda-17", "weight": 49, "ageMonths": 17, "markingId": "PM273", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-17-4", "ringId": "2174", "color": "Canelo", "cuerdaId": "cuerda-17", "weight": 55, "ageMonths": 12, "markingId": "PM274", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-18-3", "ringId": "2183", "color": "Moro", "cuerdaId": "cuerda-18", "weight": 53, "ageMonths": 19, "markingId": "PM283", "breederPlateId": "PC108", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-18-4", "ringId": "2184", "color": "Búlico", "cuerdaId": "cuerda-18", "weight": 61, "ageMonths": 20, "markingId": "PM284", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-19-3", "ringId": "2193", "color": "Jiro", "cuerdaId": "cuerda-19", "weight": 45, "ageMonths": 14, "markingId": "PM293", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-19-4", "ringId": "2194", "color": "Colorado", "cuerdaId": "cuerda-19", "weight": 64, "ageMonths": 18, "markingId": "PM294", "breederPlateId": "PC109", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-20-3", "ringId": "2203", "color": "Cenizo", "cuerdaId": "cuerda-20", "weight": 50, "ageMonths": 15, "markingId": "PM303", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-20-4", "ringId": "2204", "color": "Pinto", "cuerdaId": "cuerda-20", "weight": 58, "ageMonths": 16, "markingId": "PM304", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-21-3", "ringId": "2213", "color": "Cenizo", "cuerdaId": "cuerda-21", "weight": 51, "ageMonths": 15, "markingId": "PM213", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-21-4", "ringId": "2214", "color": "Pinto", "cuerdaId": "cuerda-21", "weight": 58, "ageMonths": 16, "markingId": "PM214", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-22-3", "ringId": "2223", "color": "Blanco", "cuerdaId": "cuerda-22", "weight": 61, "ageMonths": 13, "markingId": "PM223", "breederPlateId": "PC102", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-22-4", "ringId": "2224", "color": "Negro", "cuerdaId": "cuerda-22", "weight": 59, "ageMonths": 17, "markingId": "PM224", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-23-3", "ringId": "2233", "color": "Canelo", "cuerdaId": "cuerda-23", "weight": 47, "ageMonths": 12, "markingId": "PM233", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-23-4", "ringId": "2234", "color": "Moro", "cuerdaId": "cuerda-23", "weight": 54, "ageMonths": 19, "markingId": "PM234", "breederPlateId": "PC103", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-24-3", "ringId": "2243", "color": "Búlico", "cuerdaId": "cuerda-24", "weight": 52, "ageMonths": 20, "markingId": "PM243", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-24-4", "ringId": "2244", "color": "Jiro", "cuerdaId": "cuerda-24", "weight": 60, "ageMonths": 14, "markingId": "PM244", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-25-3", "ringId": "2253", "color": "Colorado", "cuerdaId": "cuerda-25", "weight": 46, "ageMonths": 15, "markingId": "PM253", "breederPlateId": "PC105", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-25-4", "ringId": "2254", "color": "Cenizo", "cuerdaId": "cuerda-25", "weight": 56, "ageMonths": 16, "markingId": "PM254", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-26-3", "ringId": "2263", "color": "Pinto", "cuerdaId": "cuerda-26", "weight": 63, "ageMonths": 13, "markingId": "PM263", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-26-4", "ringId": "2264", "color": "Blanco", "cuerdaId": "cuerda-26", "weight": 57, "ageMonths": 18, "markingId": "PM264", "breederPlateId": "PC106", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-27-3", "ringId": "2273", "color": "Negro", "cuerdaId": "cuerda-27", "weight": 49, "ageMonths": 17, "markingId": "PM273", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-27-4", "ringId": "2274", "color": "Canelo", "cuerdaId": "cuerda-27", "weight": 55, "ageMonths": 12, "markingId": "PM274", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-28-3", "ringId": "2283", "color": "Moro", "cuerdaId": "cuerda-28", "weight": 53, "ageMonths": 19, "markingId": "PM283", "breederPlateId": "PC108", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-28-4", "ringId": "2284", "color": "Búlico", "cuerdaId": "cuerda-28", "weight": 61, "ageMonths": 20, "markingId": "PM284", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-29-3", "ringId": "2293", "color": "Jiro", "cuerdaId": "cuerda-29", "weight": 45, "ageMonths": 14, "markingId": "PM293", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-29-4", "ringId": "2294", "color": "Colorado", "cuerdaId": "cuerda-29", "weight": 64, "ageMonths": 18, "markingId": "PM294", "breederPlateId": "PC109", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-30-3", "ringId": "2303", "color": "Cenizo", "cuerdaId": "cuerda-30", "weight": 50, "ageMonths": 15, "markingId": "PM303", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-30-4", "ringId": "2304", "color": "Pinto", "cuerdaId": "cuerda-30", "weight": 58, "ageMonths": 16, "markingId": "PM304", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 }
    ],
    "3": [
      { "id": "gallo-1-5", "ringId": "3015", "color": "Blanco", "cuerdaId": "cuerda-1", "weight": 62, "ageMonths": 13, "markingId": "PM315", "breederPlateId": "PC101", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-1-6", "ringId": "3016", "color": "Negro", "cuerdaId": "cuerda-1", "weight": 57, "ageMonths": 17, "markingId": "PM316", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-2-5", "ringId": "3025", "color": "Canelo", "cuerdaId": "cuerda-2", "weight": 48, "ageMonths": 12, "markingId": "PM325", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-2-6", "ringId": "3026", "color": "Moro", "cuerdaId": "cuerda-2", "weight": 55, "ageMonths": 19, "markingId": "PM326", "breederPlateId": "PC102", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-3-5", "ringId": "3035", "color": "Búlico", "cuerdaId": "cuerda-3", "weight": 50, "ageMonths": 20, "markingId": "PM335", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-3-6", "ringId": "3036", "color": "Jiro", "cuerdaId": "cuerda-3", "weight": 61, "ageMonths": 14, "markingId": "PM336", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-4-5", "ringId": "3045", "color": "Colorado", "cuerdaId": "cuerda-4", "weight": 46, "ageMonths": 15, "markingId": "PM345", "breederPlateId": "PC104", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-4-6", "ringId": "3046", "color": "Cenizo", "cuerdaId": "cuerda-4", "weight": 56, "ageMonths": 16, "markingId": "PM346", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-5-5", "ringId": "3055", "color": "Pinto", "cuerdaId": "cuerda-5", "weight": 63, "ageMonths": 13, "markingId": "PM355", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-5-6", "ringId": "3056", "color": "Blanco", "cuerdaId": "cuerda-5", "weight": 58, "ageMonths": 18, "markingId": "PM356", "breederPlateId": "PC105", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-6-5", "ringId": "3065", "color": "Negro", "cuerdaId": "cuerda-6", "weight": 49, "ageMonths": 17, "markingId": "PM365", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-6-6", "ringId": "3066", "color": "Canelo", "cuerdaId": "cuerda-6", "weight": 54, "ageMonths": 12, "markingId": "PM366", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-7-5", "ringId": "3075", "color": "Moro", "cuerdaId": "cuerda-7", "weight": 52, "ageMonths": 19, "markingId": "PM375", "breederPlateId": "PC107", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-7-6", "ringId": "3076", "color": "Búlico", "cuerdaId": "cuerda-7", "weight": 60, "ageMonths": 20, "markingId": "PM376", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-8-5", "ringId": "3085", "color": "Jiro", "cuerdaId": "cuerda-8", "weight": 45, "ageMonths": 14, "markingId": "PM385", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-8-6", "ringId": "3086", "color": "Colorado", "cuerdaId": "cuerda-8", "weight": 64, "ageMonths": 18, "markingId": "PM386", "breederPlateId": "PC108", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-9-5", "ringId": "3095", "color": "Cenizo", "cuerdaId": "cuerda-9", "weight": 51, "ageMonths": 15, "markingId": "PM395", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-9-6", "ringId": "3096", "color": "Pinto", "cuerdaId": "cuerda-9", "weight": 59, "ageMonths": 16, "markingId": "PM396", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-10-5", "ringId": "3105", "color": "Blanco", "cuerdaId": "cuerda-10", "weight": 62, "ageMonths": 13, "markingId": "PM405", "breederPlateId": "PC110", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-10-6", "ringId": "3106", "color": "Negro", "cuerdaId": "cuerda-10", "weight": 57, "ageMonths": 17, "markingId": "PM406", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-11-5", "ringId": "3115", "color": "Blanco", "cuerdaId": "cuerda-11", "weight": 62, "ageMonths": 13, "markingId": "PM315", "breederPlateId": "PC101", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-11-6", "ringId": "3116", "color": "Negro", "cuerdaId": "cuerda-11", "weight": 57, "ageMonths": 17, "markingId": "PM316", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-12-5", "ringId": "3125", "color": "Canelo", "cuerdaId": "cuerda-12", "weight": 48, "ageMonths": 12, "markingId": "PM325", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-12-6", "ringId": "3126", "color": "Moro", "cuerdaId": "cuerda-12", "weight": 55, "ageMonths": 19, "markingId": "PM326", "breederPlateId": "PC102", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-13-5", "ringId": "3135", "color": "Búlico", "cuerdaId": "cuerda-13", "weight": 50, "ageMonths": 20, "markingId": "PM335", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-13-6", "ringId": "3136", "color": "Jiro", "cuerdaId": "cuerda-13", "weight": 61, "ageMonths": 14, "markingId": "PM336", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-14-5", "ringId": "3145", "color": "Colorado", "cuerdaId": "cuerda-14", "weight": 46, "ageMonths": 15, "markingId": "PM345", "breederPlateId": "PC104", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-14-6", "ringId": "3146", "color": "Cenizo", "cuerdaId": "cuerda-14", "weight": 56, "ageMonths": 16, "markingId": "PM346", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-15-5", "ringId": "3155", "color": "Pinto", "cuerdaId": "cuerda-15", "weight": 63, "ageMonths": 13, "markingId": "PM355", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-15-6", "ringId": "3156", "color": "Blanco", "cuerdaId": "cuerda-15", "weight": 58, "ageMonths": 18, "markingId": "PM356", "breederPlateId": "PC105", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-16-5", "ringId": "3165", "color": "Negro", "cuerdaId": "cuerda-16", "weight": 49, "ageMonths": 17, "markingId": "PM365", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-16-6", "ringId": "3166", "color": "Canelo", "cuerdaId": "cuerda-16", "weight": 54, "ageMonths": 12, "markingId": "PM366", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-17-5", "ringId": "3175", "color": "Moro", "cuerdaId": "cuerda-17", "weight": 52, "ageMonths": 19, "markingId": "PM375", "breederPlateId": "PC107", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-17-6", "ringId": "3176", "color": "Búlico", "cuerdaId": "cuerda-17", "weight": 60, "ageMonths": 20, "markingId": "PM376", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-18-5", "ringId": "3185", "color": "Jiro", "cuerdaId": "cuerda-18", "weight": 45, "ageMonths": 14, "markingId": "PM385", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-18-6", "ringId": "3186", "color": "Colorado", "cuerdaId": "cuerda-18", "weight": 64, "ageMonths": 18, "markingId": "PM386", "breederPlateId": "PC108", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-19-5", "ringId": "3195", "color": "Cenizo", "cuerdaId": "cuerda-19", "weight": 51, "ageMonths": 15, "markingId": "PM395", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-19-6", "ringId": "3196", "color": "Pinto", "cuerdaId": "cuerda-19", "weight": 59, "ageMonths": 16, "markingId": "PM396", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-20-5", "ringId": "3205", "color": "Blanco", "cuerdaId": "cuerda-20", "weight": 62, "ageMonths": 13, "markingId": "PM405", "breederPlateId": "PC110", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-20-6", "ringId": "3206", "color": "Negro", "cuerdaId": "cuerda-20", "weight": 57, "ageMonths": 17, "markingId": "PM406", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-21-5", "ringId": "3215", "color": "Blanco", "cuerdaId": "cuerda-21", "weight": 62, "ageMonths": 13, "markingId": "PM315", "breederPlateId": "PC101", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-21-6", "ringId": "3216", "color": "Negro", "cuerdaId": "cuerda-21", "weight": 57, "ageMonths": 17, "markingId": "PM316", "breederPlateId": "PC101", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-22-5", "ringId": "3225", "color": "Canelo", "cuerdaId": "cuerda-22", "weight": 48, "ageMonths": 12, "markingId": "PM325", "breederPlateId": "PC102", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-22-6", "ringId": "3226", "color": "Moro", "cuerdaId": "cuerda-22", "weight": 55, "ageMonths": 19, "markingId": "PM326", "breederPlateId": "PC102", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-23-5", "ringId": "3235", "color": "Búlico", "cuerdaId": "cuerda-23", "weight": 50, "ageMonths": 20, "markingId": "PM335", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-23-6", "ringId": "3236", "color": "Jiro", "cuerdaId": "cuerda-23", "weight": 61, "ageMonths": 14, "markingId": "PM336", "breederPlateId": "PC103", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-24-5", "ringId": "3245", "color": "Colorado", "cuerdaId": "cuerda-24", "weight": 46, "ageMonths": 15, "markingId": "PM345", "breederPlateId": "PC104", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-24-6", "ringId": "3246", "color": "Cenizo", "cuerdaId": "cuerda-24", "weight": 56, "ageMonths": 16, "markingId": "PM346", "breederPlateId": "PC104", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-25-5", "ringId": "3255", "color": "Pinto", "cuerdaId": "cuerda-25", "weight": 63, "ageMonths": 13, "markingId": "PM355", "breederPlateId": "PC105", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-25-6", "ringId": "3256", "color": "Blanco", "cuerdaId": "cuerda-25", "weight": 58, "ageMonths": 18, "markingId": "PM356", "breederPlateId": "PC105", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-26-5", "ringId": "3265", "color": "Negro", "cuerdaId": "cuerda-26", "weight": 49, "ageMonths": 17, "markingId": "PM365", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 },
      { "id": "gallo-26-6", "ringId": "3266", "color": "Canelo", "cuerdaId": "cuerda-26", "weight": 54, "ageMonths": 12, "markingId": "PM366", "breederPlateId": "PC106", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 10 },
      { "id": "gallo-27-5", "ringId": "3275", "color": "Moro", "cuerdaId": "cuerda-27", "weight": 52, "ageMonths": 19, "markingId": "PM375", "breederPlateId": "PC107", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 3 },
      { "id": "gallo-27-6", "ringId": "3276", "color": "Búlico", "cuerdaId": "cuerda-27", "weight": 60, "ageMonths": 20, "markingId": "PM376", "breederPlateId": "PC107", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 2 },
      { "id": "gallo-28-5", "ringId": "3285", "color": "Jiro", "cuerdaId": "cuerda-28", "weight": 45, "ageMonths": 14, "markingId": "PM385", "breederPlateId": "PC108", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 8 },
      { "id": "gallo-28-6", "ringId": "3286", "color": "Colorado", "cuerdaId": "cuerda-28", "weight": 64, "ageMonths": 18, "markingId": "PM386", "breederPlateId": "PC108", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 4 },
      { "id": "gallo-29-5", "ringId": "3295", "color": "Cenizo", "cuerdaId": "cuerda-29", "weight": 51, "ageMonths": 15, "markingId": "PM395", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 7 },
      { "id": "gallo-29-6", "ringId": "3296", "color": "Pinto", "cuerdaId": "cuerda-29", "weight": 59, "ageMonths": 16, "markingId": "PM396", "breederPlateId": "PC109", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 6 },
      { "id": "gallo-30-5", "ringId": "3305", "color": "Blanco", "cuerdaId": "cuerda-30", "weight": 62, "ageMonths": 13, "markingId": "PM405", "breederPlateId": "PC110", "tipoGallo": "pava", "tipoEdad": "Gallo", "marca": 9 },
      { "id": "gallo-30-6", "ringId": "3306", "color": "Negro", "cuerdaId": "cuerda-30", "weight": 57, "ageMonths": 17, "markingId": "PM406", "breederPlateId": "PC110", "tipoGallo": "Liso", "tipoEdad": "Gallo", "marca": 5 }
    ]
  }
};

/**
 * Ensures that the raw gallo data from JSON matches the application's Gallo interface.
 * @param g The raw gallo object from JSON.
 * @returns A validated and typed Gallo object.
 */
const mapGallo = (g: any): Gallo => ({
  ...g,
  tipoGallo: g.tipoGallo === 'Liso' ? TipoGallo.LISO : TipoGallo.PAVA,
  // The provided JSON includes tipoEdad, but we can recalculate to be safe and consistent.
  tipoEdad: g.ageMonths < 12 ? TipoEdad.POLLO : TipoEdad.GALLO,
});

/**
 * Provides initial data for the application.
 * When a user starts the application for the first time without any data in localStorage,
 * this function is called to provide a pre-filled demo tournament.
 */
export const processPreloadedData = (): { cuerdas: Cuerda[], gallosByDay: Record<number, Gallo[]>, torneo: Torneo } => {
    
    const torneo: Torneo = preloadedJSON.torneo;
    const cuerdas: Cuerda[] = preloadedJSON.cuerdas;
    const gallosByDay: Record<number, Gallo[]> = {};

    const sourceGallosByDay = preloadedJSON.gallosByDay as { [key: string]: any[] };

    for (const dayKey in sourceGallosByDay) {
        const dayNum = parseInt(dayKey, 10);
        if (!isNaN(dayNum)) {
            gallosByDay[dayNum] = sourceGallosByDay[dayKey].map(mapGallo);
        }
    }

    return {
        torneo,
        cuerdas,
        gallosByDay,
    };
};
